//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOderingSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTbl()
        {
            this.EmployeeLogins = new HashSet<EmployeeLogin>();
        }
        public int EmployeeInfoID { get; set; }

        [Required(ErrorMessage = "Empty Field")]
        [Display(Name ="Employee Name")]
        public string EmployeeName { get; set; }

        [Required(ErrorMessage = "Empty Field")]
        [Display(Name = "Employee Address")]
        public string EmployeeAddress { get; set; }

        [Required(ErrorMessage = "Empty Field")]
        [Display(Name = "Employee Contact")]
        public string EmployeeContactNo { get; set; }
        [Display(Name = "Designation")]
        public string EmployeeDesignation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLogin> EmployeeLogins { get; set; }
    }
}
