//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOderingSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodOrderingProjectEntities3 : DbContext
    {
        public FoodOrderingProjectEntities3()
            : base("name=FoodOrderingProjectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTbl> CategoryTbls { get; set; }
        public virtual DbSet<CustomerTbl> CustomerTbls { get; set; }
        public virtual DbSet<EmployeeLogin> EmployeeLogins { get; set; }
        public virtual DbSet<EmployeeTbl> EmployeeTbls { get; set; }
        public virtual DbSet<OrderDetailTbl> OrderDetailTbls { get; set; }
        public virtual DbSet<OrderTbl> OrderTbls { get; set; }
        public virtual DbSet<OwnerLoginTbl> OwnerLoginTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
    }
}
