//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOderingSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTbl
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual CustomerTbl CustomerTbl { get; set; }
        public virtual OrderTbl OrderTbl { get; set; }
        public virtual ProductTbl ProductTbl { get; set; }
    }
}
