//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOderingSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderTbl
    {
        public int OrderID { get; set; }

        [Required(ErrorMessage = "Empty Field are not Allowed")]
        [Display(Name = "Order Date")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Required(ErrorMessage = "First Register The Customer")]
        [Display(Name = "Customer Name")]
        public Nullable<int> CustomerID { get; set; }
        public int Qnty { get; set; }
        [Required(ErrorMessage = "Empty Field are not Allowed")]
        [Display(Name = "Product Name")]
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public Nullable<int> TotalBill { get; set; }
    
        public virtual CustomerTbl CustomerTbl { get; set; }
        public virtual ProductTbl ProductTbl { get; set; }
        public virtual ProductTbl ProductTbl1 { get; set; }
    }
}
