//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOderingSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OwnerLoginTbl
    {
       
        public int OwnerLoginID { get; set; }
        [Required(ErrorMessage = "Avoid Empty Field")]
        [Display(Name = "AdminName")]
        public string Ownername { get; set; }
        [Required(ErrorMessage ="Avoid Empty Field")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string OwnerPassword { get; set; }
    }
}
