//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOderingSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTbl()
        {
            this.OrderTbls = new HashSet<OrderTbl>();
            this.OrderTbls1 = new HashSet<OrderTbl>();
        }
    
        public int ProductID { get; set; }
        [Required(ErrorMessage = "Empty Field are not Allowed")]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Empty Field are not Allowed")]
        [Display(Name = "Product Price")]
        public Nullable<int> ProductPrice { get; set; }
        [Required(ErrorMessage = "Product must be link with Category")]
        [Display(Name = "Product Name")]
        public Nullable<int> CategoryID { get; set; }
    
        public virtual CategoryTbl CategoryTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTbl> OrderTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTbl> OrderTbls1 { get; set; }
    }
}
